build-dpdk: add missing dependency package
To fix the following error info when build dpdk:
----------------------------------------------
In file included from /usr/include/stdio.h:27:0,
from lib/librte_eal/linuxapp/eal/eal.c:35:
/usr/include/features.h:361:25: fatal error: sys/cdefs.h: No such file or directory
-----------------------------------------------

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>