repo: remove redundant ath repo
This one is identical with ath6kl, but lack of git_am_branch, and may
lead to false report.

>
> On 03/22/2016 04:14 PM, kbuild test robot wrote:
>>
>> Hi Peter,
>>
>> [auto build test WARNING on wireless-drivers-next/master]
>> [also build test WARNING on v4.5 next-20160322]
>> [if your patch is applied to the wrong git tree, please drop us a note to
>> help improving the system]
>>
>> url:
>> https://github.com/0day-ci/linux/commits/Peter-Oh/ath10k-parse-Rx-MAC-timestamp-in-mgmt-frame-for-FW-10-4/20160323-064843
>> base:
>> https://git.kernel.org/pub/scm/linux/kernel/git/kvalo/wireless-drivers-next.git
>> master
>> config: x86_64-randconfig-x000-201612 (attached as .config)
>> reproduce:
>>          # save the attached .config to linux build tree
>>          make ARCH=x86_64
>>
>> All warnings (new ones prefixed by >>):
>>
>>     In file included from include/linux/linkage.h:4:0,
>>                      from include/linux/kernel.h:6,
>>                      from include/linux/skbuff.h:17,
>>                      from drivers/net/wireless/ath/ath10k/wmi.c:18:
>>     drivers/net/wireless/ath/ath10k/wmi.c: In function
>> 'ath10k_wmi_10_4_op_pull_mgmt_rx_ev':
>>     drivers/net/wireless/ath/ath10k/wmi.c:2236:33: error:
>> 'WMI_RX_STATUS_EXT_INFO' undeclared (first use in this function)
>
> it seems the warning is false report. I could see WMI_RX_STATUS_EXT_INFO is
> defined in wmi.h.
> Moreover this check command doesn't claim any warning/error make
> M=drivers/net/wireless/ath/ath10k C=2 CF="-D__CHECK_ENDIAN__"

I think the problem here is buildbot tested your patch against
wireless-drivers-next tree which doesn't include the macro yet. The
macro is in ath.git though.

Signed-off-by: Xiaolong Ye <xiaolong.ye@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>