build-dpdk: remove x86_x32-native-linuxapp-gcc config support
when compile dpdk with x86_x32-native-linuxapp-gcc config, will get the below error info:
----------------------------------------------------------------------------
make[5]: *** [eal_common_launch.o] Error 1
In file included from /usr/include/features.h:385:0,
                 from /usr/include/stdio.h:27,
                 from lib/librte_eal/linuxapp/eal/eal.c:35:
/usr/include/gnu/stubs.h:13:28: fatal error: gnu/stubs-x32.h: No such file or directory
compilation terminated.
make: *** [all] Error 2
----------------------------------------------------------------------------

to solve the issue, need to compile glibc source code with specfic option such as "-mx32",
(and this also enable CONFIG_X86_X32 option in kernel)

due to cannot use "apt-get install" to fix this, so we disable this config support temporarily.

detailed info can check:
https://sourceware.org/glibc/wiki/x32
https://jira01.devtools.intel.com/browse/OLT-881

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>