build-dpdk: add missing dependency package
when use v4.4 kernel to generate relevent header file and others, will get the below error info:
---------------------------------------------
In file included from /usr/include/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:45:
/usr/include/linux/errno.h:1:23: fatal error: asm/errno.h: No such file or directory
compilation terminated.
In file included from /usr/include/sys/socket.h:38:0,
                 from lib/librte_eal/linuxapp/eal/eal_pci_vfio.c:38:
/usr/include/bits/socket.h:349:24: fatal error: asm/socket.h: No such file or directory
---------------------------------------------

to fix this issue, need to install libssl-dev.

detailed info can check:
http://www.cyberciti.biz/faq/debian-ubuntu-building-installing-a-custom-linux-kernel/
https://jira01.devtools.intel.com/browse/OLT-881

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>